const ActionTypes = {
    FETCH_USERS: 'FETCH_USERS',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAIL: 'FETCH_USERS_FAIL',

    CREATE_USER: 'CREATE_USER',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    FETCH_GROUPS: 'FETCH_GROUPS',
    FETCH_GROUPS_SUCCESS: 'FETCH_GROUPS_SUCCESS',
    FETCH_GROUPS_FAIL: 'FETCH_GROUPS_FAIL',

    CREATE_GROUP: 'CREATE_GROUP',
    CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
    CREATE_GROUP_FAIL: 'CREATE_GROUP_FAIL'
};

export default ActionTypes;