const ActionTypes = {

    // USER ACTIONS

    FETCH_USERS: 'FETCH_USERS',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAIL: 'FETCH_USERS_FAIL',

    FETCH_USER: 'FETCH_USER',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAIL: 'FETCH_USER_FAIL',
    RESET_ACTIVE_USER: 'RESET_ACTIVE_USER',

    CREATE_USER: 'CREATE_USER',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',

    ADD_GROUP_TO_USER: 'ADD_GROUP_TO_USER',
    ADD_GROUP_TO_USER_SUCCESS: 'ADD_GROUP_TO_USER_SUCCESS',
    ADD_GROUP_TO_USER_FAIL: 'ADD_GROUP_TO_USER_FAIL',

    // GROUP ACTIONS

    FETCH_GROUPS: 'FETCH_GROUPS',
    FETCH_GROUPS_SUCCESS: 'FETCH_GROUPS_SUCCESS',
    FETCH_GROUPS_FAIL: 'FETCH_GROUPS_FAIL',

    FETCH_GROUP: 'FETCH_GROUP',
    FETCH_GROUP_SUCCESS: 'FETCH_GROUP_SUCCESS',
    FETCH_GROUP_FAIL: 'FETCH_GROUP_FAIL',
    RESET_ACTIVE_GROUP: 'RESET_ACTIVE_GROUP',

    CREATE_GROUP: 'CREATE_GROUP',
    CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
    CREATE_GROUP_FAIL: 'CREATE_GROUP_FAIL',

    UPDATE_GROUP: 'UPDATE_GROUP',
    UPDATE_GROUP_SUCCESS: 'UPDATE_GROUP_SUCCESS',
    UPDATE_GROUP_FAIL: 'UPDATE_GROUP_FAIL'
};

export default ActionTypes;